baseURL = ''
languageCode = 'ko-ko'
title = 'Escapee ê°œë°œë¸”ë¡œê·¸'
theme = 'PaperMod'

[params]
  ShowPostNavLinks = true

[params.homeInfoParams]
   Title = 'Escapee ğŸ’»'
   Content = 'ì˜ˆë¹„ í”„ë¡ íŠ¸ì—”ë“œ ê°œë°œì'


[manu]

[[menu.main]]
  name = 'Home'
  weight = 1
  url = '/'

[[menu.main]]
  name = 'tags'
  weight = 2
  identifier = 'tag'
  url = '/tags/'

[[menu.main]]
  name = 'Archives'
  weight = 3
  identifier = 'archives'
  url = '/archives/'
